version: "3"
services:
  web-admin:
    image: gsbelarus/gdmn-mob.web-admin:1.1.4
    container_name: web-admin
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
     - ${ADMIN_HOST_PORT}:${ADMIN_CONTAINER_PORT}
    expose:
     - ${ADMIN_CONTAINER_PORT}
    volumes:
      - ./ssl:/web-admin/ssl:ro
  server:
    image: gsbelarus/gdmn-mob.server:0.2.5
    container_name: server
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - FILES_PATH=/var/lib/gdmn-mob_db
    ports:
      - ${PORT}:${PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    volumes:
      - db:/var/lib/gdmn-mob_db
      - ./ssl:/server/ssl:ro
volumes:
  db:
